// Deterministic Chinese/Western zodiac sign computation from a stored
// ISO birthdate (YYYY-MM-DD) — see entities.birthdate, lib/db.ts. Used by
// the Journal-tab sidebar (Part 6) and the Horoscope tab's synastry chart
// (Part 7). Sign computation itself is pure math; only the reflection TEXT
// that accompanies a sign is ever generated by Claude — see
// lib/zodiacContent.ts.

// 12-year cycle anchored on 2020 = Year of the Rat (a recent, unambiguous
// reference point). This is the standard Gregorian-year approximation used
// by virtually every mainstream zodiac app — it does NOT account for the
// exact Lunar New Year cutoff (which falls in late Jan/early Feb and would
// occasionally shift someone born in that window to the previous animal).
// Accepted as a known, minor limitation rather than pulling in a full
// lunar calendar library for it.
export const CHINESE_ZODIAC_SIGNS = [
  "Rat",
  "Ox",
  "Tiger",
  "Rabbit",
  "Dragon",
  "Snake",
  "Horse",
  "Goat",
  "Monkey",
  "Rooster",
  "Dog",
  "Pig",
] as const;
export type ChineseZodiacSign = (typeof CHINESE_ZODIAC_SIGNS)[number];

export const WESTERN_ZODIAC_SIGNS = [
  "Aries",
  "Taurus",
  "Gemini",
  "Cancer",
  "Leo",
  "Virgo",
  "Libra",
  "Scorpio",
  "Sagittarius",
  "Capricorn",
  "Aquarius",
  "Pisces",
] as const;
export type WesternZodiacSign = (typeof WESTERN_ZODIAC_SIGNS)[number];

function parseIsoDate(birthdate: string): { year: number; month: number; day: number } | null {
  const match = birthdate.trim().match(/^(\d{4})-(\d{2})-(\d{2})/);
  if (!match) return null;
  return { year: Number(match[1]), month: Number(match[2]), day: Number(match[3]) };
}

export function getChineseZodiacSign(birthdate: string): ChineseZodiacSign | null {
  const parsed = parseIsoDate(birthdate);
  if (!parsed) return null;
  const offset = ((parsed.year - 2020) % 12 + 12) % 12;
  return CHINESE_ZODIAC_SIGNS[offset]!;
}

// Standard tropical Western zodiac date ranges. Boundary dates use the most
// commonly published cutoffs; a birthday landing exactly on a cusp date
// resolves to the sign whose range the day-of-month check below assigns it
// to (matches convention used by most mainstream zodiac references).
export function getWesternZodiacSign(birthdate: string): WesternZodiacSign | null {
  const parsed = parseIsoDate(birthdate);
  if (!parsed) return null;
  const { month, day } = parsed;

  if ((month === 3 && day >= 21) || (month === 4 && day <= 19)) return "Aries";
  if ((month === 4 && day >= 20) || (month === 5 && day <= 20)) return "Taurus";
  if ((month === 5 && day >= 21) || (month === 6 && day <= 20)) return "Gemini";
  if ((month === 6 && day >= 21) || (month === 7 && day <= 22)) return "Cancer";
  if ((month === 7 && day >= 23) || (month === 8 && day <= 22)) return "Leo";
  if ((month === 8 && day >= 23) || (month === 9 && day <= 22)) return "Virgo";
  if ((month === 9 && day >= 23) || (month === 10 && day <= 22)) return "Libra";
  if ((month === 10 && day >= 23) || (month === 11 && day <= 21)) return "Scorpio";
  if ((month === 11 && day >= 22) || (month === 12 && day <= 21)) return "Sagittarius";
  if ((month === 12 && day >= 22) || (month === 1 && day <= 19)) return "Capricorn";
  if ((month === 1 && day >= 20) || (month === 2 && day <= 18)) return "Aquarius";
  return "Pisces"; // Feb 19 – Mar 20
}

// Every zodiac icon asset lives flat under public/assets/, named exactly
// after the sign (Tiger.png, Aries.png, ...) — see public/assets/. Sign
// names above already match those filenames verbatim, so this is just the
// URL path, not a lookup table.
export function zodiacIconUrl(sign: ChineseZodiacSign | WesternZodiacSign): string {
  return `/assets/${sign}.png`;
}
