// Deterministic Chinese/Western zodiac sign computation from a stored
// ISO birthdate (YYYY-MM-DD) — see entities.birthdate, lib/db.ts. Used by
// the Journal-tab sidebar (Part 6) and the Horoscope tab's synastry chart
// (Part 7). Sign computation itself is pure math; only the reflection TEXT
// that accompanies a sign is ever generated by Claude — see
// lib/zodiacContent.ts.

// 12-year cycle anchored on 2020 = Year of the Rat (a recent, unambiguous
// reference point). This is the standard Gregorian-year approximation used
// by virtually every mainstream zodiac app — it does NOT account for the
// exact Lunar New Year cutoff (which falls in late Jan/early Feb and would
// occasionally shift someone born in that window to the previous animal).
// Accepted as a known, minor limitation rather than pulling in a full
// lunar calendar library for it.
export const CHINESE_ZODIAC_SIGNS = [
  "Rat",
  "Ox",
  "Tiger",
  "Rabbit",
  "Dragon",
  "Snake",
  "Horse",
  "Goat",
  "Monkey",
  "Rooster",
  "Dog",
  "Pig",
] as const;
export type ChineseZodiacSign = (typeof CHINESE_ZODIAC_SIGNS)[number];

export const WESTERN_ZODIAC_SIGNS = [
  "Aries",
  "Taurus",
  "Gemini",
  "Cancer",
  "Leo",
  "Virgo",
  "Libra",
  "Scorpio",
  "Sagittarius",
  "Capricorn",
  "Aquarius",
  "Pisces",
] as const;
export type WesternZodiacSign = (typeof WESTERN_ZODIAC_SIGNS)[number];

/**
 * Item 7's third distinct root cause (beyond extraction never producing a
 * birthdate attribute at all, and the sidebar never re-fetching mid-
 * session — both fixed separately): the extraction prompt deliberately
 * records a birthdate's value "as literally asserted" (taxonomySchema.ts),
 * by design, for provenance — so a user who types "4/24/1970" gets exactly
 * that string stored, not a silently-reformatted one. This function used
 * to accept ONLY strict ISO (YYYY-MM-DD) and returned null on anything
 * else, which is exactly what happened live: a real, valid, unambiguous
 * date was stored correctly and then silently failed to parse here, so
 * the sidebar stayed locked even after a real fix elsewhere. Also accepts
 * the common US M/D/YYYY or MM/DD/YYYY form.
 *
 * Exported (R36/R37, attribute-integrity fix): also the ONE format
 * validator src/perception/attributes.ts's shared resolveAttribute uses to
 * decide whether a stored birthdate value is well-formed — never a second,
 * separately-maintained date parser that could drift from this one.
 */
export function parseIsoDate(birthdate: string): { year: number; month: number; day: number } | null {
  const trimmed = birthdate.trim();
  const iso = trimmed.match(/^(\d{4})-(\d{2})-(\d{2})/);
  if (iso) return { year: Number(iso[1]), month: Number(iso[2]), day: Number(iso[3]) };
  const us = trimmed.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
  if (us) return { year: Number(us[3]), month: Number(us[1]), day: Number(us[2]) };
  return null;
}

export function getChineseZodiacSign(birthdate: string): ChineseZodiacSign | null {
  const parsed = parseIsoDate(birthdate);
  if (!parsed) return null;
  const offset = ((parsed.year - 2020) % 12 + 12) % 12;
  return CHINESE_ZODIAC_SIGNS[offset]!;
}

/** The current calendar year's own Chinese zodiac animal (2026 = Horse) — same anchor/approximation as getChineseZodiacSign, just applied to today's year instead of a birth year. Used for the sidebar's year-vs-person angle (EN-031). */
export function getCurrentChineseYearSign(now: Date = new Date()): ChineseZodiacSign {
  const offset = (((now.getFullYear() - 2020) % 12) + 12) % 12;
  return CHINESE_ZODIAC_SIGNS[offset]!;
}

// Standard tropical Western zodiac date ranges. Boundary dates use the most
// commonly published cutoffs; a birthday landing exactly on a cusp date
// resolves to the sign whose range the day-of-month check below assigns it
// to (matches convention used by most mainstream zodiac references).
export function getWesternZodiacSign(birthdate: string): WesternZodiacSign | null {
  const parsed = parseIsoDate(birthdate);
  if (!parsed) return null;
  const { month, day } = parsed;

  if ((month === 3 && day >= 21) || (month === 4 && day <= 19)) return "Aries";
  if ((month === 4 && day >= 20) || (month === 5 && day <= 20)) return "Taurus";
  if ((month === 5 && day >= 21) || (month === 6 && day <= 20)) return "Gemini";
  if ((month === 6 && day >= 21) || (month === 7 && day <= 22)) return "Cancer";
  if ((month === 7 && day >= 23) || (month === 8 && day <= 22)) return "Leo";
  if ((month === 8 && day >= 23) || (month === 9 && day <= 22)) return "Virgo";
  if ((month === 9 && day >= 23) || (month === 10 && day <= 22)) return "Libra";
  if ((month === 10 && day >= 23) || (month === 11 && day <= 21)) return "Scorpio";
  if ((month === 11 && day >= 22) || (month === 12 && day <= 21)) return "Sagittarius";
  if ((month === 12 && day >= 22) || (month === 1 && day <= 19)) return "Capricorn";
  if ((month === 1 && day >= 20) || (month === 2 && day <= 18)) return "Aquarius";
  return "Pisces"; // Feb 19 – Mar 20
}

// Every zodiac icon asset lives flat under public/assets/, named exactly
// after the sign (Tiger.png, Aries.png, ...) — see public/assets/. Sign
// names above already match those filenames verbatim, so this is just the
// URL path, not a lookup table.
export function zodiacIconUrl(sign: ChineseZodiacSign | WesternZodiacSign): string {
  return `/assets/${sign}.png`;
}
